#!/bin/bash -l
#PBS -l walltime=100:00:00
#PBS -l nodes=1:ppn=24:haswell
#PBS #-l #pmem=5gb
#PBS -N Run_Slope_Paper_3
#PBS -A lp_uncertainty_quantification


module purge
module load matlab/R2019a
cd julia-1.2.0/bin/
./julia /vsc-hard-mounts/leuven-user/330/vsc33032/.julia/packages/MultilevelEstimators/KoRDo/applications/SPDE/Run_Slope_Stability_GP_non_nested.jl 2>&1 | tee /vsc-hard-mounts/leuven-user/330/vsc33032/.julia/packages/MultilevelEstimators/KoRDo/applications/SPDE/Slope_hpc_02042020_NonNested_100steps_16_MLQMC_Only.txt

